### ISSUE TITLE
[Bug] Lint baseline is not generated

### ISSUE THREAD

**Issue by saurabharora90** [slackhq/foundry#813]
https://github.com/slackhq/slack-gradle-plugin/blob/2670eb302109c6b15f60008d1314802b144c5427/slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt#L341

Lint is not generating a baseline.xml when using the Lint task from this plugin. The issue seems to that the baseline file is being configured in library modules as well, whereas instead it should only be done for Application Modules. Adding a 
```
if (androidExtensionNullable is ApplicationAndroidComponentsExtension)
```
before configuring the baseline file seems to resolve the issue. Given `checkDependencies` is enabled for app modules, it makes sense to enable baseline also just for app modules. 

I have this working locally and can send a PR if you are open to contributions and agree with the change. Didn't file it under discussion as it was more of a bug than a feature request :)

**Comment by ZacSweers** [comment]
sorry for the delay on this!

> it should only be done for Application Modules

I'm not sure I follow this. We run lint with baselines on both library and application projects. In our application project, we _only_ run lint with UnusedResources and nothing else. Could you elaborate on why you think this option only applies to application projects?

**Comment by ZacSweers** [comment]
Closing this for now!
